### ISSUE TITLE
Multi-zoom Level mbtiles

### ISSUE THREAD

**Issue by miles-dev** [mapbox/mbtiles-extracts#8]
When running mbtiles-extracts on an mbtiles file with multiple zoom levels, the output does not retain the correct data at all zoom levels as found in the input. The resulting file will have the input data split across multiple zoom levels so that it appears to pop in and out as you zoom on the map.

As an example, let's assume a city is broken up into thirds A, B, and C with data in the mbtiles files existing in all three areas at all zoom levels. After running this through mbtiles-extracts, you would find that the data for section A only shows up at z9-z11, the data for section B shows up for z9+, and the data for section C only shows up for z11+. Zooming out, no data would appear for anything < z9.

Desired functionality is that the mbtiles-extracts script handles mbtiles files across all zoom levels of the input data so that we don't have this inconsistent result.

/cc @geohacker @mourner @ryanbaumann @mtirwin

**Comment by ryanbaumann** [comment]
@miles-dev can you link a sample mbtiles file on an s3 bucket we can test with for this issue?

**Comment by mourner** [comment]
Capturing from chat:

My guess on what’s going on is the mbtiles-extracts determines whether a tile belongs to the boundary by probing the tile’s centerpoint; this doesn’t work well for lower zoom level tiles because their centerpoint can lie outside the boundary. Since the script doesn’t actually do any data clipping along the boundary, but just sorts already present tiles in an mbtiles file, the tiles on the boundary are less likely to get included the lower the zoom.

There’s a relatively easy fix for this — `which-polygon` module (which is a dependency) can also query by bbox and return boundaries that intersect it; however the effect of that fix will be that lower zooms will have more data than higher zooms (because there’s no splitting along the boundary going on, and lower zoom tiles along the boundary are bigger than higher zoom tiles). If that’s OK, I can make a quick PR.

**Comment by mourner** [comment]
Actually I just realized that there's already a PR for this exact problem: https://github.com/mapbox/mbtiles-extracts/pull/7 — @miles-dev can you check if that branch works in your case?

**Comment by miles-dev** [comment]
Thanks @mourner. The branch you linked to does get us closer. It solved the multi-zoom level issue. We still have an issue from our end goal in that the current mbtiles-extracts functionality cuts via tiles and not geometries. Closing out this ticket as we have addressed the original concerns here and we will continue to investigate the functionality we want elsewhere.
